---
- name: Deploy Blood Banking System on Ubuntu (Localhost)
  hosts: all
  become: yes
  vars:
    project_name: blood-banking-system
    mysql_root_password: Abhi@9142
    mysql_database: bloodbank
    backend_image: abhi9142/bloodbank-backend:v2
    frontend_image: abhi9142/bloodbank-frontend:v2
    docker_network: bloodbank-network

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - software-properties-common
          - python3-pip
        state: present

    - name: Install Docker Python module
      pip:
        name:
          - docker
          - docker-compose
        state: present

    - name: Check if Docker is installed
      command: docker --version
      register: docker_installed
      ignore_errors: yes
      changed_when: false

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: docker_installed.rc != 0

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
      when: docker_installed.rc != 0

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: yes
      when: docker_installed.rc != 0

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Create Docker network
      community.docker.docker_network:
        name: "{{ docker_network }}"
        state: present

    - name: Create MySQL data volume
      community.docker.docker_volume:
        name: mysql_data
        state: present

    - name: Stop existing MySQL container
      community.docker.docker_container:
        name: bloodbank_mysql
        state: absent
      ignore_errors: yes

    - name: Run MySQL container
      community.docker.docker_container:
        name: bloodbank_mysql
        image: mysql:8.0
        state: started
        restart_policy: always
        networks:
          - name: "{{ docker_network }}"
        published_ports:
          - "3306:3306"
        env:
          MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
          MYSQL_DATABASE: "{{ mysql_database }}"
        volumes:
          - mysql_data:/var/lib/mysql

    - name: Wait for MySQL to be ready
      wait_for:
        host: localhost
        port: 3306
        delay: 10
        timeout: 60

    - name: Pull Backend Docker image
      community.docker.docker_image:
        name: "{{ backend_image }}"
        source: pull

    - name: Stop existing Backend container
      community.docker.docker_container:
        name: bloodbank_backend
        state: absent
      ignore_errors: yes

    - name: Run Backend container
      community.docker.docker_container:
        name: bloodbank_backend
        image: "{{ backend_image }}"
        state: started
        restart_policy: always
        networks:
          - name: "{{ docker_network }}"
        published_ports:
          - "8081:8081"
        env:
          SPRING_DATASOURCE_URL: "jdbc:mysql://bloodbank_mysql:3306/{{ mysql_database }}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: "{{ mysql_root_password }}"
          SPRING_JPA_HIBERNATE_DDL_AUTO: update
          SERVER_PORT: "8081"

    - name: Wait for Backend to be ready
      wait_for:
        host: localhost
        port: 8081
        delay: 15
        timeout: 120

    - name: Pull Frontend Docker image
      community.docker.docker_image:
        name: "{{ frontend_image }}"
        source: pull

    - name: Stop existing Frontend container
      community.docker.docker_container:
        name: bloodbank_frontend
        state: absent
      ignore_errors: yes

    - name: Run Frontend container
      community.docker.docker_container:
        name: bloodbank_frontend
        image: "{{ frontend_image }}"
        state: started
        restart_policy: always
        networks:
          - name: "{{ docker_network }}"
        published_ports:
          - "5173:5173"
        env:
          VITE_API_URL: http://localhost:8081

    - name: Wait for Frontend to be ready
      wait_for:
        host: localhost
        port: 5173
        delay: 5
        timeout: 60

    - name: Get container status
      command: docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"
      register: container_status
      changed_when: false

    - name: Display deployment summary
      debug:
        msg:
          - "=========================================="
          - "Blood Banking System Deployed Successfully!"
          - "=========================================="
          - "Frontend URL: http://localhost:5173"
          - "Backend API: http://localhost:8081"
          - "Database: MySQL 8.0 on localhost:3306"
          - "=========================================="
          - "Container Status:"
          - "{{ container_status.stdout }}"
          - "=========================================="
