---
- name: Deploy Blood Banking System on Ubuntu (Localhost - Docker Only)
  hosts: localhost
  gather_facts: yes
  vars:
    mysql_root_password: "Abhi@9142"
    mysql_database: "bloodbank"
    backend_image: "abhi9142/bloodbank-backend:v2"
    frontend_image: "abhi9142/bloodbank-frontend:v2"
    network_name: "bloodbank-network"

  tasks:
    - name: Stop existing MySQL container
      community.docker.docker_container:
        name: bloodbank_mysql
        state: absent
      ignore_errors: yes

    - name: Stop existing backend container
      community.docker.docker_container:
        name: bloodbank_backend
        state: absent
      ignore_errors: yes

    - name: Stop existing frontend container
      community.docker.docker_container:
        name: bloodbank_frontend
        state: absent
      ignore_errors: yes

    - name: Remove existing Docker network
      community.docker.docker_network:
        name: "{{ network_name }}"
        state: absent
      ignore_errors: yes

    - name: Create Docker network
      community.docker.docker_network:
        name: "{{ network_name }}"
        state: present

    - name: Pull MySQL image
      community.docker.docker_image:
        name: mysql:8.0
        source: pull

    - name: Pull backend image
      community.docker.docker_image:
        name: "{{ backend_image }}"
        source: pull

    - name: Pull frontend image
      community.docker.docker_image:
        name: "{{ frontend_image }}"
        source: pull

    - name: Deploy MySQL container
      community.docker.docker_container:
        name: bloodbank_mysql
        image: mysql:8.0
        state: started
        restart_policy: always
        networks:
          - name: "{{ network_name }}"
        env:
          MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
          MYSQL_DATABASE: "{{ mysql_database }}"
        ports:
          - "3307:3306"
        volumes:
          - bloodbank_mysql_data:/var/lib/mysql

    - name: Wait for MySQL to be ready
      wait_for:
        host: localhost
        port: 3307
        delay: 10
        timeout: 60
        state: started

    - name: Deploy backend container
      community.docker.docker_container:
        name: bloodbank_backend
        image: "{{ backend_image }}"
        state: started
        restart_policy: always
        networks:
          - name: "{{ network_name }}"
        env:
          SPRING_DATASOURCE_URL: "jdbc:mysql://bloodbank_mysql:3306/{{ mysql_database }}"
          SPRING_DATASOURCE_USERNAME: "root"
          SPRING_DATASOURCE_PASSWORD: "{{ mysql_root_password }}"
        ports:
          - "8082:8081"

    - name: Wait for backend to be ready
      wait_for:
        host: localhost
        port: 8082
        delay: 15
        timeout: 120
        state: started

    - name: Deploy frontend container
      community.docker.docker_container:
        name: bloodbank_frontend
        image: "{{ frontend_image }}"
        state: started
        restart_policy: always
        networks:
          - name: "{{ network_name }}"
        ports:
          - "5174:5173"

    - name: Wait for frontend to be ready
      wait_for:
        host: localhost
        port: 5174
        delay: 5
        timeout: 30
        state: started

    - name: Display deployment status
      debug:
        msg:
          - "========================================="
          - "Blood Banking System Deployment Complete!"
          - "========================================="
          - "Frontend: http://localhost:5174"
          - "Backend API: http://localhost:8082"
          - "MySQL: localhost:3307"
          - "========================================="
          - "Containers Running:"
          - "  - bloodbank_mysql"
          - "  - bloodbank_backend"
          - "  - bloodbank_frontend"
          - "========================================="

    - name: Verify all containers are running
      shell: docker ps --filter "name=bloodbank_" --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"
      register: container_status
      changed_when: false

    - name: Show container status
      debug:
        var: container_status.stdout_lines
